server {
    listen 80;
    server_name _;
    root /var/www/public;

    # Tamaño máximo de archivos (debe coincidir con PHP)
    client_max_body_size 50M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    # Logs
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # Timeouts para archivos grandes
        fastcgi_read_timeout 300;
        fastcgi_send_timeout 300;
        
        # Buffers para archivos grandes
        fastcgi_buffering on;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 16 16k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Para assets de Vite/Tailwind
    location /build {
        try_files $uri =404;
    }
    
    # Para archivos subidos
    location /storage {
        try_files $uri =404;
    }
}